-- MySQL Script generated by MySQL Workbench
-- Sat Apr 19 18:23:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zp_db` DEFAULT CHARACTER SET utf8 ;
USE `zp_db` ;

-- -----------------------------------------------------
-- Table `mydb`.`pouzivatelia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zp_db`.`pouzivatelia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meno` VARCHAR(15) NOT NULL,
  `priezvisko` VARCHAR(10) NOT NULL,
  `heslo` VARCHAR(45) NOT NULL,
  `datum_vytvorenia` DATETIME NOT NULL,
  `rola` TINYINT NOT NULL,
  `datum_posledneho_prihlasenia` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clanky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zp_db`.`clanky` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazov` VARCHAR(20) NOT NULL,
  `datum` DATETIME NOT NULL,
  `pouzivatelia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_clanky_pouzivatelia`
    FOREIGN KEY (`pouzivatelia_id`)
    REFERENCES `zp_db`.`pouzivatelia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_clanky_pouzivatelia_idx` ON `zp_db`.`clanky` (`pouzivatelia_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zp_db`.`kategorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazov` VARCHAR(15) NOT NULL,
  `podkategoria` INT NULL,
  `kategorie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_kategorie_kategorie1`
    FOREIGN KEY (`kategorie_id`)
    REFERENCES `zp_db`.`kategorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_kategorie_kategorie1_idx` ON `zp_db`.`kategorie` (`kategorie_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`kategorie_clanky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zp_db`.`kategorie_clanky` (
  `kategorie_id` INT NOT NULL,
  `clanky_id` INT NOT NULL,
  CONSTRAINT `fk_kategorie_clanky_kategorie1`
    FOREIGN KEY (`kategorie_id`)
    REFERENCES `zp_db`.`kategorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kategorie_clanky_clanky1`
    FOREIGN KEY (`clanky_id`)
    REFERENCES `zp_db`.`clanky` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_kategorie_clanky_kategorie1_idx` ON `zp_db`.`kategorie_clanky` (`kategorie_id` ASC);

CREATE INDEX `fk_kategorie_clanky_clanky1_idx` ON `zp_db`.`kategorie_clanky` (`clanky_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
